import { join } from 'node:path'
import { Command } from 'commander'

import { createAction, splitCsv } from '../runtime.js'
import type { CliProgramDeps } from '../runtime.js'
import { detectOnboardProject } from '../onboard-detect.js'
import { executeOnboard, renderOnboardPlan } from '../onboard-executor.js'
import type { ImportSpecInput } from '../types.js'
import { validateLocalGitRepositoryPath } from './repositories.js'

interface OnboardOptions {
  project?: string
  mergeMode: 'auto' | 'human'
  setup: string[]
  verify: string[]
  requiredFile: string[]
  importSampleSpec?: boolean
  specName?: string
  taskName?: string
  force?: boolean
  dryRun?: boolean
}

export function registerOnboardCommand(program: Command, deps: CliProgramDeps): void {
  program
    .command('onboard <path>')
    .description('Create or update a Project from an existing local repository')
    .option('--project <name>', 'Project name; defaults to repository directory name')
    .option('--merge-mode <mode>', 'Merge mode for newly created Projects', 'human')
    .option('--setup <command>', 'Setup command for the workflow profile', splitCsv, [])
    .option('--verify <command>', 'Verification command for the workflow profile', splitCsv, [])
    .option('--required-file <path>', 'Required file gate for the workflow profile', splitCsv, [])
    .option('--import-sample-spec', 'Import a starter Spec/Task after onboarding the repository')
    .option('--spec-name <name>', 'Starter Spec name used with --import-sample-spec')
    .option('--task-name <name>', 'Starter Task name used with --import-sample-spec')
    .option('--force', 'Overwrite an existing .edictum/workflow-profile.yaml')
    .option('--dry-run', 'Print the onboarding plan without writing files or API writes')
    .action(createAction(deps, async (ctx, rawPath: string, options: OnboardOptions) => {
      const repoPath = validateLocalGitRepositoryPath(rawPath, 'path')
      const detection = detectOnboardProject(repoPath, {
        projectName: options.project,
        setupCommands: options.setup,
        verifyCommands: options.verify,
        requiredFiles: options.requiredFile,
      })
      const profilePath = join(repoPath, '.edictum', 'workflow-profile.yaml')
      const input = {
        repoPath,
        profilePath,
        profile: renderWorkflowProfile(detection),
        detection,
        mergeMode: options.mergeMode,
        force: options.force === true,
        dryRun: options.dryRun === true,
        starterSpec: options.importSampleSpec === true
          ? buildStarterSpec(detection, {
              specName: options.specName,
              taskName: options.taskName,
            })
          : null,
      }
      const execution = await executeOnboard(ctx.api, input)
      ctx.write(
        { repoPath, profilePath, profile: input.profile, starterSpec: input.starterSpec, ...detection, execution },
        renderOnboardPlan(input, execution),
      )
    }))
}

function renderWorkflowProfile(input: ReturnType<typeof detectOnboardProject>): string {
  return [
    'apiVersion: edictum/v1alpha1',
    'kind: WorkflowProfile',
    'metadata:',
    `  name: ${yamlString(input.projectName)}`,
    `  description: ${yamlString(`Generated by ductum onboard for ${input.stack}`)}`,
    'context:',
    '  required_files:',
    ...input.requiredFiles.map((file) => `    - ${yamlString(file)}`),
    '  optional_files:',
    ...input.optionalFiles.map((file) => `    - ${yamlString(file)}`),
    ...(input.setupCommands.length === 0 ? [] : ['setup:', '  commands:', ...input.setupCommands.map((command) => `    - ${yamlString(command)}`)]),
    'verify:',
    '  commands:',
    ...input.verifyCommands.map((command) => `    - ${yamlString(command)}`),
    'push:',
    '  protected_branches:',
    '    - main',
    '  allowed_git_commands:',
    '    - git status',
    '    - git diff',
    '    - git add',
    '    - git commit',
    '',
  ].join('\n')
}

function buildStarterSpec(
  input: ReturnType<typeof detectOnboardProject>,
  options: { specName?: string; taskName?: string },
): ImportSpecInput {
  const specName = options.specName ?? `${input.projectName} onboarding`
  const taskName = options.taskName ?? 'Verify onboarded repository'
  return {
    spec: {
      name: specName,
      status: 'approved',
      document: [
        `# ${specName}`,
        '',
        'Generated by ductum onboard. The first task proves the detected workflow profile can run.',
      ].join('\n'),
    },
    tasks: [{
      name: taskName,
      prompt: [
        'Verify the onboarded repository using the generated WorkflowProfile.',
        'Read the required project files first, make the smallest useful change if the task requires one, and run the verification command.',
      ].join(' '),
      repos: [],
      requiredRole: 'builder',
      verification: input.verifyCommands,
    }],
  }
}

function yamlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}
