import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { DuctumApi } from '../api-client.js'
import { Command } from 'commander'

import { formatSummaryRows } from '../format.js'
import { createAction, splitCsv } from '../runtime.js'
import type { CliProgramDeps } from '../runtime.js'
import { detectOnboardProject } from '../onboard-detect.js'
import type { ImportSpecInput, ImportSpecResult } from '../types.js'
import { validateLocalGitRepositoryPath } from './repositories.js'

interface OnboardOptions {
  project?: string
  mergeMode: 'auto' | 'human'
  setup: string[]
  verify: string[]
  requiredFile: string[]
  importSampleSpec?: boolean
  specName?: string
  taskName?: string
  force?: boolean
  dryRun?: boolean
}

export function registerOnboardCommand(program: Command, deps: CliProgramDeps): void {
  program
    .command('onboard <path>')
    .description('Create or update a Project from an existing local repository')
    .option('--project <name>', 'Project name; defaults to repository directory name')
    .option('--merge-mode <mode>', 'Merge mode for newly created Projects', 'human')
    .option('--setup <command>', 'Setup command for the workflow profile', splitCsv, [])
    .option('--verify <command>', 'Verification command for the workflow profile', splitCsv, [])
    .option('--required-file <path>', 'Required file gate for the workflow profile', splitCsv, [])
    .option('--import-sample-spec', 'Import a starter Spec/Task after onboarding the repository')
    .option('--spec-name <name>', 'Starter Spec name used with --import-sample-spec')
    .option('--task-name <name>', 'Starter Task name used with --import-sample-spec')
    .option('--force', 'Overwrite an existing .edictum/workflow-profile.yaml')
    .option('--dry-run', 'Print the onboarding plan without writing files or calling the API')
    .action(createAction(deps, async (ctx, rawPath: string, options: OnboardOptions) => {
      const repoPath = validateLocalGitRepositoryPath(rawPath, 'path')
      const detection = detectOnboardProject(repoPath, {
        projectName: options.project,
        setupCommands: options.setup,
        verifyCommands: options.verify,
        requiredFiles: options.requiredFile,
      })
      const profilePath = join(repoPath, '.edictum', 'workflow-profile.yaml')
      const profile = renderWorkflowProfile(detection)
      const starterSpec = options.importSampleSpec === true
        ? buildStarterSpec(detection, {
            specName: options.specName,
            taskName: options.taskName,
          })
        : null
      if (options.dryRun === true) {
        ctx.write({ repoPath, profilePath, profile, starterSpec, ...detection }, renderPlan(repoPath, profilePath, detection, {
          dryRun: true,
          importedSpec: null,
          starterSpec,
        }))
        return
      }

      writeWorkflowProfile(profilePath, profile, options.force === true)
      const existing = await findProject(ctx.api, detection.projectName)
      const project = existing ?? await ctx.api.createProject({
        name: detection.projectName,
        repositories: [{ localPath: repoPath }],
        config: { mergeMode: options.mergeMode, workflowProfile: profilePath },
      })
      if (existing != null) {
        await ctx.api.createRepository(project.id, { localPath: repoPath })
      }
      const importedSpec = starterSpec == null ? null : await ctx.api.importSpec(project.id, starterSpec)
      ctx.write(
        { project, repoPath, profilePath, stack: detection.stack, verifyCommands: detection.verifyCommands, importedSpec },
        renderPlan(repoPath, profilePath, detection, {
          dryRun: false,
          importedSpec,
          starterSpec,
        }),
      )
    }))
}

function renderWorkflowProfile(input: ReturnType<typeof detectOnboardProject>): string {
  return [
    'apiVersion: edictum/v1alpha1',
    'kind: WorkflowProfile',
    'metadata:',
    `  name: ${yamlString(input.projectName)}`,
    `  description: ${yamlString(`Generated by ductum onboard for ${input.stack}`)}`,
    'context:',
    '  required_files:',
    ...input.requiredFiles.map((file) => `    - ${yamlString(file)}`),
    '  optional_files:',
    ...input.optionalFiles.map((file) => `    - ${yamlString(file)}`),
    ...(input.setupCommands.length === 0 ? [] : ['setup:', '  commands:', ...input.setupCommands.map((command) => `    - ${yamlString(command)}`)]),
    'verify:',
    '  commands:',
    ...input.verifyCommands.map((command) => `    - ${yamlString(command)}`),
    'push:',
    '  protected_branches:',
    '    - main',
    '  allowed_git_commands:',
    '    - git status',
    '    - git diff',
    '    - git add',
    '    - git commit',
    '    - git push',
    '',
  ].join('\n')
}

function writeWorkflowProfile(path: string, content: string, force: boolean): void {
  if (existsSync(path) && !force) {
    throw new Error(`${path} already exists; pass --force to overwrite`)
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

async function findProject(api: DuctumApi, name: string) {
  const projects = await api.listProjects()
  return projects.find((project) => project.name === name) ?? null
}

function renderPlan(
  repoPath: string,
  profilePath: string,
  detection: ReturnType<typeof detectOnboardProject>,
  options: {
    dryRun: boolean
    importedSpec: ImportSpecResult | null
    starterSpec: ImportSpecInput | null
  },
): string {
  const summaryInput: Record<string, string> = {
    project: detection.projectName,
    stack: detection.stack,
    repo: repoPath,
    workflowProfile: profilePath,
    verify: detection.verifyCommands.join(', '),
  }
  if (options.starterSpec != null) {
    summaryInput.starterSpec = options.starterSpec.spec.name
  }
  const summary = formatSummaryRows(summaryInput)
  const suffix = options.dryRun
    ? 'dry-run: no files written and no API calls made'
    : options.importedSpec != null
      ? `next: ductum task list ${options.importedSpec.spec.id}`
      : 'next: ductum doctor --json'
  return `${summary}\n${suffix}`
}

function buildStarterSpec(
  input: ReturnType<typeof detectOnboardProject>,
  options: { specName?: string; taskName?: string },
): ImportSpecInput {
  const specName = options.specName ?? `${input.projectName} onboarding`
  const taskName = options.taskName ?? 'Verify onboarded repository'
  return {
    spec: {
      name: specName,
      status: 'approved',
      document: [
        `# ${specName}`,
        '',
        'Generated by ductum onboard. The first task proves the detected workflow profile can run.',
      ].join('\n'),
    },
    tasks: [{
      name: taskName,
      prompt: [
        'Verify the onboarded repository using the generated WorkflowProfile.',
        'Read the required project files first, make the smallest useful change if the task requires one, and run the verification command.',
      ].join(' '),
      repos: [],
      requiredRole: 'builder',
      verification: input.verifyCommands,
    }],
  }
}

function yamlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}
