import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'

import { detectOnboardProject } from '../onboard-detect.js'
import { executeOnboard } from '../onboard-executor.js'
import { createMockApi, project, repository, runCommand, spec } from './helpers.js'

const tempDirs: string[] = []

afterEach(() => {
  for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true })
})

describe('ductum onboard command', () => {
  it('writes a WorkflowProfile and creates a Project for a local repo', async () => {
    const repoPath = nodeRepo()
    const api = createMockApi({
      listProjects: vi.fn().mockResolvedValue([]),
      createProject: vi.fn().mockResolvedValue({ ...project, name: 'sample' }),
    })

    const result = await runCommand(['onboard', repoPath, '--project', 'sample'], api)
    const profile = readFileSync(join(repoPath, '.edictum', 'workflow-profile.yaml'), 'utf8')

    expect(result.code).toBe(0)
    expect(api.createProject).toHaveBeenCalledWith({
      name: 'sample',
      repositories: [{ localPath: repoPath }],
      config: { mergeMode: 'human', workflowProfile: join(repoPath, '.edictum', 'workflow-profile.yaml') },
    })
    expect(profile).toContain('kind: WorkflowProfile')
    expect(profile).toContain("    - 'README.md'")
    expect(profile).toContain("    - 'pnpm install --frozen-lockfile'")
    expect(profile).toContain("    - 'pnpm test'")
    expect(result.text).toContain('projectAction')
    expect(result.text).toContain('next: ductum doctor --json')
  })

  it('adds a repository when the Project already exists', async () => {
    const repoPath = nodeRepo()
    const api = createMockApi({
      listProjects: vi.fn().mockResolvedValue([{ ...project, name: 'existing' }]),
      createRepository: vi.fn().mockResolvedValue({ ...repository, spec: { localPath: repoPath } }),
    })

    const result = await runCommand(['onboard', repoPath, '--project', 'existing'], api)

    expect(result.code).toBe(0)
    expect(api.createProject).not.toHaveBeenCalled()
    expect(api.createRepository).toHaveBeenCalledWith(project.id, { localPath: repoPath })
    expect(result.text).toContain('attach-repository')
  })

  it('can import a starter spec after onboarding the repository', async () => {
    const repoPath = nodeRepo()
    const api = createMockApi({
      listProjects: vi.fn().mockResolvedValue([]),
      createProject: vi.fn().mockResolvedValue({ ...project, name: 'sample' }),
      importSpec: vi.fn().mockResolvedValue({ spec: { ...spec, id: 'spec-onboard' }, taskCount: 1 }),
    })

    const result = await runCommand([
      'onboard',
      repoPath,
      '--project',
      'sample',
      '--import-sample-spec',
      '--spec-name',
      'Starter',
      '--task-name',
      'Smoke',
    ], api)

    expect(result.code).toBe(0)
    expect(api.importSpec).toHaveBeenCalledWith(project.id, {
      spec: {
        name: 'Starter',
        status: 'approved',
        document: expect.stringContaining('Generated by ductum onboard'),
      },
      tasks: [{
        name: 'Smoke',
        prompt: expect.stringContaining('Verify the onboarded repository'),
        repos: [],
        requiredRole: 'builder',
        verification: ['pnpm test'],
      }],
    })
    expect(result.text).toContain('starterSpecTasks')
    expect(result.text).toContain('next: ductum task list spec-onboard')
  })

  it('dry-runs through the same read path while stubbing writes', async () => {
    const repoPath = nodeRepo()
    const api = createMockApi({ listProjects: vi.fn().mockResolvedValue([]) })

    const result = await runCommand(['onboard', repoPath, '--project', 'dry', '--dry-run'], api)

    expect(result.code).toBe(0)
    expect(existsSync(join(repoPath, '.edictum', 'workflow-profile.yaml'))).toBe(false)
    expect(api.listProjects).toHaveBeenCalledTimes(1)
    expect(api.createProject).not.toHaveBeenCalled()
    expect(api.createRepository).not.toHaveBeenCalled()
    expect(api.importSpec).not.toHaveBeenCalled()
    expect(result.text).toContain('dry-run: writes stubbed; no files or API writes were performed')
  })

  it('ties dry-run and apply behavior to the same action summary', async () => {
    const repoPath = nodeRepo()
    const detection = detectOnboardProject(repoPath, { projectName: 'sample' })
    const input = {
      repoPath,
      profilePath: join(repoPath, '.edictum', 'workflow-profile.yaml'),
      profile: 'kind: WorkflowProfile\n',
      detection,
      mergeMode: 'human' as const,
      force: true,
      starterSpec: {
        spec: { name: 'Starter', status: 'approved' as const, document: '# Starter' },
        tasks: [{ name: 'Smoke', prompt: 'Plan', repos: [], verification: ['pnpm test'], requiredRole: 'builder' as const }],
      },
    }
    const dryApi = createMockApi({ listProjects: vi.fn().mockResolvedValue([]) })
    const applyApi = createMockApi({
      listProjects: vi.fn().mockResolvedValue([]),
      createProject: vi.fn().mockResolvedValue({ ...project, name: 'sample' }),
      importSpec: vi.fn().mockResolvedValue({ spec: { ...spec, id: 'spec-onboard' }, taskCount: 1 }),
    })

    const dryRun = await executeOnboard(dryApi, { ...input, dryRun: true })
    const applyRun = await executeOnboard(applyApi, { ...input, dryRun: false })

    expect(dryRun).toMatchObject({
      workflowProfileAction: applyRun.workflowProfileAction,
      projectAction: applyRun.projectAction,
      starterSpecAction: applyRun.starterSpecAction,
      starterSpecTaskCount: applyRun.starterSpecTaskCount,
    })
    expect(dryApi.createProject).not.toHaveBeenCalled()
    expect(applyApi.createProject).toHaveBeenCalledTimes(1)
  })

  it('refuses to overwrite an existing WorkflowProfile without --force', async () => {
    const repoPath = nodeRepo()
    writeFileSync(join(repoPath, '.edictum', 'workflow-profile.yaml'), 'existing')
    const api = createMockApi({ listProjects: vi.fn().mockResolvedValue([]) })

    const result = await runCommand(['onboard', repoPath, '--project', 'sample'], api)

    expect(result.code).toBe(1)
    expect(result.errorText).toContain('already exists; pass --force to overwrite')
    expect(api.listProjects).not.toHaveBeenCalled()
  })
})

function nodeRepo(): string {
  const dir = mkdtempSync(join(tmpdir(), 'ductum-onboard-'))
  tempDirs.push(dir)
  execFileSync('git', ['init'], { cwd: dir, stdio: 'ignore' })
  writeFileSync(join(dir, 'README.md'), '# sample\n')
  writeFileSync(join(dir, 'pnpm-lock.yaml'), 'lockfileVersion: 9.0\n')
  writeFileSync(join(dir, 'package.json'), JSON.stringify({ scripts: { test: 'vitest run' } }))
  mkdirSync(join(dir, '.edictum'))
  return dir
}
