import Database from 'better-sqlite3'
import { describe, expect, it } from 'vitest'

import { applyMigration, MIGRATIONS } from '../db-migrations.js'

const LEGACY_MARKER = 'Multi-agent bakeoff generated by ductum spec bakeoff.'

describe('best-of-n strategy metadata migration', () => {
  it('backfills only exact legacy bakeoff records', () => {
    const db = createPreBestOfNSchema()
    seedLegacyRows(db)

    applyMigration(db, bestOfNMigration())
    applyMigration(db, bestOfNMigration())

    expect(db.prepare("SELECT COUNT(*) AS count FROM pragma_table_info('specs') WHERE name = 'strategy_config'").get()).toEqual({
      count: 1,
    })
    expect(db.prepare('SELECT strategy FROM specs WHERE id = ?').get('legacy-spec')).toEqual({
      strategy: 'best_of_n',
    })
    expect(db.prepare('SELECT strategy FROM specs WHERE id = ?').get('plain-spec')).toEqual({
      strategy: 'normal',
    })
    expect(
      db
        .prepare('SELECT name, strategy_role, strategy_group FROM tasks ORDER BY id')
        .all(),
    ).toEqual([
      {
        name: 'candidate-codex',
        strategy_role: 'candidate',
        strategy_group: 'legacy-legacy-spec',
      },
      {
        name: 'blind-review',
        strategy_role: 'blind_review',
        strategy_group: 'legacy-legacy-spec',
      },
      {
        name: 'candidate-bakeoff-looking',
        strategy_role: 'normal',
        strategy_group: null,
      },
    ])

    db.close()
  })

  it('rejects invalid strategy values', () => {
    const db = createPreBestOfNSchema()
    applyMigration(db, bestOfNMigration())

    expect(() =>
      db.prepare(
        "INSERT INTO specs (id, project_id, name, status, document, strategy) VALUES ('bad-spec', 'p', 'bad', 'draft', '', 'bakeoff')",
      ).run(),
    ).toThrow(/CHECK/)
    expect(() =>
      db.prepare(
        "INSERT INTO tasks (id, spec_id, name, prompt, status, verification, strategy_role) VALUES ('bad-task', 'bad-spec', 'bad', '', 'pending', '[]', 'judge')",
      ).run(),
    ).toThrow(/CHECK/)

    db.close()
  })
})

function bestOfNMigration(): (typeof MIGRATIONS)[number] {
  const migration = MIGRATIONS.find((item) => item.id === '039_best_of_n_strategy_metadata')
  if (migration == null) throw new Error('missing best-of-n migration')
  return migration
}

function createPreBestOfNSchema(): Database.Database {
  const db = new Database(':memory:')
  db.exec(`
    CREATE TABLE specs (
      id TEXT PRIMARY KEY,
      project_id TEXT NOT NULL,
      name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      document TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE TABLE tasks (
      id TEXT PRIMARY KEY,
      spec_id TEXT NOT NULL,
      name TEXT NOT NULL,
      prompt TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      verification TEXT NOT NULL DEFAULT '[]',
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `)
  return db
}

function seedLegacyRows(db: Database.Database): void {
  db.prepare(
    "INSERT INTO specs (id, project_id, name, status, document) VALUES ('legacy-spec', 'p', 'Legacy', 'approved', ?)",
  ).run(`# Legacy\n\n${LEGACY_MARKER}`)
  db.prepare(
    "INSERT INTO specs (id, project_id, name, status, document) VALUES ('plain-spec', 'p', 'Plain', 'approved', ?)",
  ).run('This mentions bakeoff but has no generated marker.')
  db.prepare(
    "INSERT INTO tasks (id, spec_id, name, prompt, status, verification) VALUES ('task-1', 'legacy-spec', 'candidate-codex', '', 'pending', '[]')",
  ).run()
  db.prepare(
    "INSERT INTO tasks (id, spec_id, name, prompt, status, verification) VALUES ('task-2', 'legacy-spec', 'blind-review', '', 'pending', '[]')",
  ).run()
  db.prepare(
    "INSERT INTO tasks (id, spec_id, name, prompt, status, verification) VALUES ('task-3', 'plain-spec', 'candidate-bakeoff-looking', '', 'pending', '[]')",
  ).run()
}
