import { describe, expect, it } from 'vitest'

import { evaluateTaskExecutionIntegrity } from '../execution-integrity.js'
import type { Evidence, Run, Spec, Task } from '../types.js'

describe('execution integrity bakeoff outcomes', () => {
  it('uses the latest explicit bakeoff candidate outcome', () => {
    const candidateRun = run()
    const integrity = evaluateTaskExecutionIntegrity(
      task({ status: 'done', name: 'candidate-codex', strategyRole: 'candidate', strategyGroup: 'bon-1' }),
      { strategy: 'best_of_n' } as Spec,
      [candidateRun],
      new Map([
        [candidateRun.id, [
          evidence({ payload: { kind: 'bakeoff-candidate-outcome', outcome: 'fixed' } }),
          evidence({ id: 'evidence-2' as Evidence['id'], payload: { kind: 'bakeoff-candidate-outcome', outcome: 'rejected' } }),
        ]],
      ]),
    )

    expect(integrity.mode).toBe('orchestrated')
    expect(integrity.bakeoffOutcome).toBe('rejected')
    expect(integrity.issues).toEqual([])
  })

  it('does not treat bakeoff-looking text or candidate names as strategy metadata', () => {
    const candidateRun = run()
    const integrity = evaluateTaskExecutionIntegrity(
      task({ status: 'done', name: 'candidate-codex' }),
      { strategy: 'normal', document: 'Multi-agent bakeoff generated by ductum spec bakeoff.' } as Spec,
      [candidateRun],
      new Map([[candidateRun.id, []]]),
    )

    expect(integrity.issues.map((issue) => issue.code)).not.toContain('bakeoff_candidate_without_outcome')
  })
})

function run(overrides: Partial<Run> = {}): Run {
  return {
    id: 'run-1' as Run['id'],
    taskId: 'task-1' as Run['taskId'],
    agentId: 'agent-1' as Run['agentId'],
    parentRunId: null,
    stage: 'done',
    terminalState: null,
    resetCount: 0,
    completedStages: [],
    blockedReason: null,
    pendingApproval: false,
    sessionId: 'session-1',
    branch: 'feat/demo',
    commitSha: 'abc123',
    prNumber: null,
    prUrl: null,
    worktreePaths: ['/tmp/worktree'],
    runtimeModel: null,
    runtimeHarness: null,
    runtimeSandboxProfile: null,
    runtimeWorkflowProfile: null,
    ciStatus: null,
    reviewStatus: null,
    failReason: null,
    recoverable: true,
    tokensIn: 0,
    tokensOut: 0,
    costUsd: 0,
    lastHeartbeat: null,
    heartbeatTimeoutSeconds: 120,
    verifyRetries: 0,
    completionSummary: null,
    createdAt: '2026-04-29T00:00:00.000Z',
    updatedAt: '2026-04-29T00:00:00.000Z',
    ...overrides,
  }
}

function task(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-1' as Task['id'],
    specId: 'spec-1' as Task['specId'],
    targetId: null,
    name: 'candidate-codex',
    prompt: '',
    repos: [],
    assignedAgentId: null,
    requiredRole: null,
    complexity: null,
    status: 'active',
    strategyRole: 'normal',
    strategyGroup: null,
    verification: [],
    retryCount: 0,
    retryAfter: null,
    budgetExtraUsd: 0,
    turnExtraCount: 0,    createdAt: '2026-04-29T00:00:00.000Z',
    updatedAt: '2026-04-29T00:00:00.000Z',
    ...overrides,
  }
}

function evidence(overrides: Partial<Evidence> = {}): Evidence {
  return {
    id: 'evidence-1' as Evidence['id'],
    runId: 'run-1' as Evidence['runId'],
    type: 'custom',
    payload: {},
    createdAt: '2026-04-29T00:00:00.000Z',
    ...overrides,
  }
}
