import {
  AGENT_CAPABILITIES,
  AGENT_ROLES,
  EVIDENCE_TYPES,
  SPEC_STATUSES,
  TASK_COMPLEXITIES,
  TASK_STATUSES,
  TERMINAL_STATES,
  WORKFLOW_STAGES,
} from './types.js'
import { EVIDENCE_KINDS } from './evidence-kinds.js'
import { MCP_AGENT_TOOL_CONTRACT } from './mcp-tool-contract.js'

export const AUTHORING_CONTRACT_VERSION = 'ductum.authoring-contract.v1'

export interface AuthoringContractFile {
  path: 'llms.txt' | 'llms-full.txt' | 'docs/tool-examples-convention.md'
  content: string
}

export function buildAuthoringContractFiles(): AuthoringContractFile[] {
  return [
    { path: 'llms.txt', content: buildLlmsTxt() },
    { path: 'llms-full.txt', content: buildLlmsFullTxt() },
    { path: 'docs/tool-examples-convention.md', content: buildToolExamplesConvention() },
  ]
}

function buildLlmsTxt(): string {
  return lines([
    '# Ductum Agent Authoring Contract',
    '',
    `Version: ${AUTHORING_CONTRACT_VERSION}`,
    'Generated by scripts/generate-authoring-contract.mjs. Do not edit by hand.',
    '',
    'Ductum is a governed factory: Factory -> Project -> Repository/Component -> Spec -> Task -> Attempt.',
    'Author valid artifacts; Ductum still enforces workflow gates at runtime.',
    '',
    'Use /llms-full.txt for complete shapes. This index covers the safe authoring path.',
    '',
    'Core rules:',
    '- Agents never pass run_id. MCP sessions are bound by the server.',
    '- Agents do not self-reset. Ductum Core owns retries, resets, resume, quarantine, and failover.',
    '- Call ductum.workflow first on a bound run, then satisfy the current stage gates.',
    '- Validity is not correctness. Include real verification commands and evidence.',
    '',
    'WorkflowProfile skeleton:',
    '```yaml',
    'apiVersion: edictum/v1alpha1',
    'kind: WorkflowProfile',
    'metadata:',
    '  name: coding-guard',
    'context:',
    '  required_files: [README.md]',
    '  optional_files: []',
    'verify:',
    '  commands: [pnpm test]',
    'push:',
    '  protected_branches: [main]',
    '  allowed_git_commands: [git status, git diff, git add, git commit, git push]',
    '```',
    '',
    `Workflow stages: ${WORKFLOW_STAGES.join(', ')}`,
    `Spec statuses: ${SPEC_STATUSES.join(', ')}`,
    `Task statuses: ${TASK_STATUSES.join(', ')}`,
    `Agent roles: ${AGENT_ROLES.join(', ')}`,
    `MCP tools: ${MCP_AGENT_TOOL_CONTRACT.map((tool) => tool.name).join(', ')}`,
  ])
}

function buildLlmsFullTxt(): string {
  return lines([
    '# Ductum Full Agent Authoring Contract',
    '',
    `Version: ${AUTHORING_CONTRACT_VERSION}`,
    'Generated by scripts/generate-authoring-contract.mjs. Do not edit by hand.',
    '',
    '## Primitive Model',
    '',
    'Factory owns global settings. Project groups repositories. Repository may have Components.',
    'Spec contains Tasks. Task dispatch creates Attempts. Attempts move through Workflow stages.',
    '',
    '## Enumerations',
    '',
    bullet('workflowStages', WORKFLOW_STAGES),
    bullet('terminalStates', TERMINAL_STATES),
    bullet('specStatuses', SPEC_STATUSES),
    bullet('taskStatuses', TASK_STATUSES),
    bullet('taskComplexities', TASK_COMPLEXITIES),
    bullet('agentRoles', AGENT_ROLES),
    bullet('agentCapabilities', AGENT_CAPABILITIES),
    bullet('evidenceTypes', EVIDENCE_TYPES),
    bullet('typedEvidenceKinds', Object.keys(EVIDENCE_KINDS)),
    '',
    '## WorkflowProfile YAML',
    '',
    'Required fields: apiVersion, kind, metadata.name, context.required_files, verify.commands, push.',
    'context.required_files and verify.commands must each contain at least one string.',
    'context.optional_files and setup.commands default to empty arrays when omitted.',
    'push.protected_branches defaults to main when empty or omitted.',
    'Protected branches are reserved for the platform merge path; agents should only push feature branches.',
    '',
    '```yaml',
    'apiVersion: edictum/v1alpha1',
    'kind: WorkflowProfile',
    'metadata:',
    '  name: coding-guard',
    '  description: Guarded implementation flow',
    'context:',
    '  required_files:',
    '    - README.md',
    '  optional_files:',
    '    - AGENTS.md',
    'setup:',
    '  commands:',
    '    - pnpm install --frozen-lockfile',
    'verify:',
    '  commands:',
    '    - pnpm test',
    'review:',
    '  approval_message: Approve only after external review reports no new issues',
    'push:',
    '  protected_branches:',
    '    - main',
    '  allowed_git_commands:',
    '    - git status',
    '    - git diff',
    '    - git add',
    '    - git commit',
    '    - git push',
    '```',
    '',
    '## SpecIntake / WorkPackage JSON',
    '',
    'schemaVersion must be ductum.spec-intake.v1. Attempts are never authored; Ductum creates them at runtime.',
    '',
    '```json',
    JSON.stringify(specIntakeExample(), null, 2),
    '```',
    '',
    '## MCP Agent Tool Surface',
    '',
    ...MCP_AGENT_TOOL_CONTRACT.flatMap((tool) => [
      `### ${tool.name}`,
      tool.description,
      `Required input: ${tool.required.length === 0 ? 'none' : tool.required.join(', ')}`,
      `Input fields: ${Object.keys(tool.input).length === 0 ? 'none' : JSON.stringify(tool.input)}`,
      `Example: ${JSON.stringify(tool.example)}`,
      '',
    ]),
    '## Extension Manifest Draft',
    '',
    'Operator-allowlisted ExtensionRegistry manifest loading is shipped for capability registration. Runtime execution of arbitrary extension code is not shipped yet; entrypoint is recorded and resolved, not imported.',
    '',
    '```json',
    JSON.stringify(extensionManifestDraft(), null, 2),
    '```',
  ])
}

function buildToolExamplesConvention(): string {
  return lines([
    '# Tool Examples Convention',
    '',
    `Generated from ${AUTHORING_CONTRACT_VERSION}. Do not edit by hand.`,
    '',
    'Each agent-visible MCP tool must have 1-5 examples in the authoring contract.',
    'Examples must show only public tool inputs. Do not include run_id, operator tokens, cookies, secrets, or local absolute paths.',
    '',
    'Current tool example index:',
    '',
    ...MCP_AGENT_TOOL_CONTRACT.map((tool) => `- ${tool.name}: ${JSON.stringify(tool.example)}`),
  ])
}

function specIntakeExample() {
  return {
    schemaVersion: 'ductum.spec-intake.v1',
    project: { name: 'factory' },
    repositories: [{
      name: 'ductum',
      localPath: '.',
      components: [{ name: 'core', path: 'packages/core' }],
      tasks: [{
        name: 'Add generated authoring contract',
        prompt: 'Implement the bounded contract slice and run verification.',
        verification: ['pnpm -C packages/core test'],
        assignedAgent: 'mimi',
        complexity: 'standard',
        requiredRole: 'builder',
        status: 'pending',
      }],
    }],
    spec: { name: 'Authoring Contract', status: 'approved', document: 'Generated contract slice.' },
  }
}

function extensionManifestDraft() {
  return {
    schemaVersion: 'ductum.extension.v1',
    id: 'com.example.local-notifier',
    kind: 'notifier',
    entrypoint: './dist/index.js',
    capabilities: ['notify.run_state'],
    permissions: { network: false, secrets: [] },
  }
}

function bullet(name: string, values: readonly string[]): string {
  return `- ${name}: ${values.join(', ')}`
}

function lines(value: string[]): string {
  return `${value.join('\n')}\n`
}
