import type { Spec, Task } from './types.js'

/**
 * Historical marker kept so old records can still be recognized by humans.
 * Runtime routing must use typed strategy metadata, not this text.
 */
export const BAKEOFF_SPEC_MARKER = 'Multi-agent bakeoff generated by ductum spec bakeoff.'

export function isBakeoffSpec(
  spec: Pick<Spec, 'strategy'> | null | undefined,
): boolean {
  return spec?.strategy === 'best_of_n'
}

export function isBakeoffCandidateTask(
  spec: Pick<Spec, 'strategy'> | null | undefined,
  task: Pick<Task, 'strategyRole'>,
): boolean {
  return isBakeoffSpec(spec) && task.strategyRole === 'candidate'
}

export function isBakeoffBlindReviewTask(
  spec: Pick<Spec, 'strategy'> | null | undefined,
  task: Pick<Task, 'strategyRole'>,
): boolean {
  return isBakeoffSpec(spec) && task.strategyRole === 'blind_review'
}
