import type Database from 'better-sqlite3'

const LEGACY_BAKEOFF_SPEC_MARKER = 'Multi-agent bakeoff generated by ductum spec bakeoff.'

export const MIGRATIONS = [
  {
    id: '001_initial_schema',
    sql: `
      CREATE TABLE IF NOT EXISTS factories (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        config TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY,
        factory_id TEXT NOT NULL REFERENCES factories(id),
        name TEXT NOT NULL UNIQUE,
        repos TEXT NOT NULL DEFAULT '[]',
        config TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS agents (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        model TEXT NOT NULL,
        harness TEXT NOT NULL CHECK (harness IN ('claude-agent-sdk', 'opencode')),
        capabilities TEXT NOT NULL DEFAULT '[]',
        spawn_config TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS project_agents (
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
        role TEXT NOT NULL CHECK (role IN ('builder', 'reviewer', 'docs', 'watcher')),
        PRIMARY KEY (project_id, agent_id)
      );

      CREATE TABLE IF NOT EXISTS specs (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft'
          CHECK (status IN ('draft', 'reviewed', 'approved', 'implementing', 'done')),
        document TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS spec_dependencies (
        spec_id TEXT NOT NULL REFERENCES specs(id) ON DELETE CASCADE,
        depends_on_id TEXT NOT NULL REFERENCES specs(id) ON DELETE CASCADE,
        kind TEXT NOT NULL CHECK (kind IN ('hard', 'soft')),
        PRIMARY KEY (spec_id, depends_on_id)
      );

      CREATE TABLE IF NOT EXISTS tasks (
        id TEXT PRIMARY KEY,
        spec_id TEXT NOT NULL REFERENCES specs(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        prompt TEXT NOT NULL DEFAULT '',
        repos TEXT NOT NULL DEFAULT '[]',
        assigned_agent_id TEXT REFERENCES agents(id),
        status TEXT NOT NULL DEFAULT 'pending'
          CHECK (status IN ('pending', 'blocked', 'ready', 'active', 'done', 'failed')),
        verification TEXT NOT NULL DEFAULT '[]',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS task_dependencies (
        task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
        depends_on_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
        PRIMARY KEY (task_id, depends_on_id)
      );

      CREATE TABLE IF NOT EXISTS runs (
        id TEXT PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        agent_id TEXT NOT NULL REFERENCES agents(id),
        parent_run_id TEXT REFERENCES runs(id),
        stage TEXT NOT NULL DEFAULT 'accepted'
          CHECK (stage IN (
            'accepted', 'implementing', 'fixing', 'pre-push-review',
            'pushing', 'waiting-for-ci', 'waiting-for-review',
            'waiting-for-approval', 'merging', 'done', 'failed', 'stalled'
          )),
        session_id TEXT,
        branch TEXT,
        commit_sha TEXT,
        pr_number INTEGER,
        pr_url TEXT,
        ci_status TEXT CHECK (ci_status IN (NULL, 'pending', 'pass', 'fail')),
        review_status TEXT CHECK (review_status IN (NULL, 'pending', 'pass', 'fail')),
        fail_reason TEXT,
        recoverable INTEGER NOT NULL DEFAULT 1,
        tokens_in INTEGER NOT NULL DEFAULT 0,
        tokens_out INTEGER NOT NULL DEFAULT 0,
        cost_usd REAL NOT NULL DEFAULT 0.0,
        last_heartbeat TEXT,
        heartbeat_timeout_seconds INTEGER NOT NULL DEFAULT 120,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS decisions (
        id TEXT PRIMARY KEY,
        spec_id TEXT REFERENCES specs(id) ON DELETE SET NULL,
        task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL,
        run_id TEXT REFERENCES runs(id) ON DELETE SET NULL,
        decision TEXT NOT NULL,
        context TEXT NOT NULL,
        alternatives TEXT,
        decided_by TEXT NOT NULL,
        supersedes_id TEXT REFERENCES decisions(id),
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_runs_task_id ON runs(task_id);
      CREATE INDEX IF NOT EXISTS idx_runs_session_id ON runs(session_id) WHERE session_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_runs_stage ON runs(stage) WHERE stage NOT IN ('done', 'failed');

      CREATE TABLE IF NOT EXISTS run_stage_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        from_stage TEXT NOT NULL,
        to_stage TEXT NOT NULL,
        reason TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_run_stage_history_run ON run_stage_history(run_id);

      CREATE TABLE IF NOT EXISTS evidence (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        type TEXT NOT NULL CHECK (type IN ('ci', 'review', 'test', 'lint', 'custom', 'exit_demo.run')),
        payload TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_evidence_run ON evidence(run_id);

      CREATE TABLE IF NOT EXISTS gate_evaluations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        gate_type TEXT NOT NULL CHECK (gate_type IN ('authorize_tool', 'gate_check')),
        target TEXT NOT NULL,
        result TEXT NOT NULL CHECK (result IN ('allowed', 'blocked')),
        reason TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_gate_evaluations_run ON gate_evaluations(run_id);

      CREATE TABLE IF NOT EXISTS session_run_mapping (
        session_id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        harness TEXT NOT NULL CHECK (harness IN ('claude-agent-sdk', 'opencode')),
        control_token TEXT NOT NULL,
        working_dir TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS edictum_session_counters (
        session_id TEXT NOT NULL,
        key TEXT NOT NULL,
        value INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (session_id, key)
      );

      CREATE TABLE IF NOT EXISTS edictum_session_values (
        session_id TEXT NOT NULL,
        key TEXT NOT NULL,
        value TEXT NOT NULL,
        PRIMARY KEY (session_id, key)
      );
    `,
  },
  {
    id: '002_run_updates',
    sql: `
      CREATE TABLE IF NOT EXISTS run_updates (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        message TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_run_updates_run ON run_updates(run_id);
    `,
  },
  {
    id: '003_tasks_required_role',
    sql: `
      ALTER TABLE tasks ADD COLUMN required_role TEXT
        CHECK (required_role IN (NULL, 'builder', 'reviewer', 'docs', 'watcher'));
    `,
  },
  {
    id: '004_run_activity',
    sql: `
      CREATE TABLE IF NOT EXISTS run_activity (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        kind TEXT NOT NULL CHECK (kind IN ('tool_call', 'text', 'summary', 'result')),
        content TEXT NOT NULL,
        tool_name TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE INDEX IF NOT EXISTS idx_run_activity_run ON run_activity(run_id);
    `,
  },
  {
    id: '005_task_retry',
    sql: `
      ALTER TABLE tasks ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
      ALTER TABLE tasks ADD COLUMN retry_after TEXT;
    `,
  },
  {
    id: '006_session_run_working_dir',
    sql: `
      ALTER TABLE session_run_mapping ADD COLUMN working_dir TEXT;
    `,
  },
  {
    id: '007_session_run_control_token',
    sql: `
      ALTER TABLE session_run_mapping ADD COLUMN control_token TEXT;
      UPDATE session_run_mapping
        SET control_token = lower(hex(randomblob(32)))
        WHERE control_token IS NULL OR control_token = '';
    `,
  },
  {
    id: '008_workflow_stages',
    sql: `
      -- Rebuild runs table: replace old Ductum stages with Edictum workflow stages
      CREATE TABLE runs_new (
        id TEXT PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        agent_id TEXT NOT NULL REFERENCES agents(id),
        parent_run_id TEXT REFERENCES runs_new(id),
        stage TEXT NOT NULL DEFAULT 'read-analyze'
          CHECK (stage IN (
            'read-analyze', 'create-branch', 'baseline-verify', 'implement',
            'local-verify', 'external-review', 'docs-update', 'push-pr',
            'ci-green', 'done'
          )),
        terminal_state TEXT CHECK (terminal_state IN (NULL, 'failed', 'stalled')),
        reset_count INTEGER NOT NULL DEFAULT 0,
        completed_stages TEXT,
        blocked_reason TEXT,
        pending_approval INTEGER NOT NULL DEFAULT 0,
        session_id TEXT,
        branch TEXT,
        commit_sha TEXT,
        pr_number INTEGER,
        pr_url TEXT,
        ci_status TEXT CHECK (ci_status IN (NULL, 'pending', 'pass', 'fail')),
        review_status TEXT CHECK (review_status IN (NULL, 'pending', 'pass', 'fail')),
        fail_reason TEXT,
        recoverable INTEGER NOT NULL DEFAULT 1,
        tokens_in INTEGER NOT NULL DEFAULT 0,
        tokens_out INTEGER NOT NULL DEFAULT 0,
        cost_usd REAL NOT NULL DEFAULT 0.0,
        last_heartbeat TEXT,
        heartbeat_timeout_seconds INTEGER NOT NULL DEFAULT 120,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      INSERT INTO runs_new (
        id, task_id, agent_id, parent_run_id, stage, terminal_state,
        reset_count, completed_stages, blocked_reason, pending_approval,
        session_id, branch, commit_sha, pr_number, pr_url,
        ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, created_at, updated_at
      )
      SELECT
        id, task_id, agent_id, parent_run_id,
        CASE stage
          WHEN 'accepted' THEN 'read-analyze'
          WHEN 'implementing' THEN 'implement'
          WHEN 'fixing' THEN 'implement'
          WHEN 'pre-push-review' THEN 'external-review'
          WHEN 'pushing' THEN 'push-pr'
          WHEN 'waiting-for-ci' THEN 'ci-green'
          WHEN 'waiting-for-review' THEN 'ci-green'
          WHEN 'waiting-for-approval' THEN 'external-review'
          WHEN 'merging' THEN 'done'
          WHEN 'done' THEN 'done'
          WHEN 'failed' THEN 'implement'
          WHEN 'stalled' THEN 'implement'
          ELSE 'read-analyze'
        END AS stage,
        CASE WHEN stage = 'failed' THEN 'failed'
             WHEN stage = 'stalled' THEN 'stalled'
             ELSE NULL END AS terminal_state,
        0 AS reset_count,
        NULL AS completed_stages,
        NULL AS blocked_reason,
        0 AS pending_approval,
        session_id, branch, commit_sha, pr_number, pr_url,
        ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, created_at, updated_at
      FROM runs;

      DROP TABLE runs;
      ALTER TABLE runs_new RENAME TO runs;

      CREATE INDEX IF NOT EXISTS idx_runs_task_id ON runs(task_id);
      CREATE INDEX IF NOT EXISTS idx_runs_session_id ON runs(session_id) WHERE session_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_runs_stage ON runs(stage) WHERE stage NOT IN ('done');
      CREATE INDEX IF NOT EXISTS idx_runs_terminal ON runs(terminal_state) WHERE terminal_state IS NOT NULL;

      -- Rebuild run_stage_history to remove CHECK on old stage values
      CREATE TABLE run_stage_history_new (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        from_stage TEXT NOT NULL,
        to_stage TEXT NOT NULL,
        reason TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      INSERT INTO run_stage_history_new SELECT * FROM run_stage_history;
      DROP TABLE run_stage_history;
      ALTER TABLE run_stage_history_new RENAME TO run_stage_history;
      CREATE INDEX IF NOT EXISTS idx_run_stage_history_run ON run_stage_history(run_id);
    `,
  },
  {
    id: '009_task_complexity',
    sql: `
      ALTER TABLE tasks ADD COLUMN complexity TEXT
        CHECK (complexity IN (NULL, 'simple', 'standard', 'complex'));
    `,
  },
  {
    id: '010_agent_cost_tier',
    sql: `
      ALTER TABLE agents ADD COLUMN cost_tier INTEGER NOT NULL DEFAULT 50;
    `,
  },
  {
    id: '011_multi_role_agents',
    sql: `
      CREATE TABLE project_agents_new (
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
        role TEXT NOT NULL CHECK (role IN ('builder', 'reviewer', 'docs', 'watcher')),
        PRIMARY KEY (project_id, agent_id, role)
      );
      INSERT INTO project_agents_new SELECT * FROM project_agents;
      DROP TABLE project_agents;
      ALTER TABLE project_agents_new RENAME TO project_agents;
    `,
  },
  {
    id: '012_harness_vercel_ai',
    sql: `
      CREATE TABLE agents_new (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        model TEXT NOT NULL,
        harness TEXT NOT NULL CHECK (harness IN ('claude-agent-sdk', 'vercel-ai', 'openai-agents', 'codex-app-server', 'codex-sdk')),
        capabilities TEXT NOT NULL DEFAULT '[]',
        cost_tier INTEGER NOT NULL DEFAULT 50,
        spawn_config TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO agents_new SELECT * FROM agents;
      DROP TABLE agents;
      ALTER TABLE agents_new RENAME TO agents;

      CREATE TABLE session_run_mapping_new (
        session_id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        harness TEXT NOT NULL CHECK (harness IN ('claude-agent-sdk', 'vercel-ai', 'openai-agents', 'codex-app-server', 'codex-sdk')),
        control_token TEXT,
        working_dir TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO session_run_mapping_new SELECT * FROM session_run_mapping;
      DROP TABLE session_run_mapping;
      ALTER TABLE session_run_mapping_new RENAME TO session_run_mapping;
    `,
  },
  {
    id: '013_worktree_paths',
    sql: `
      ALTER TABLE runs ADD COLUMN worktree_paths TEXT;
    `,
  },
  {
    id: '014_three_stage_workflow',
    sql: `
      -- Rebuild runs table: collapse 9-stage workflow into 3-stage (understand, implement, ship, done)
      CREATE TABLE runs_new (
        id TEXT PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        agent_id TEXT NOT NULL REFERENCES agents(id),
        parent_run_id TEXT REFERENCES runs_new(id),
        stage TEXT NOT NULL DEFAULT 'understand'
          CHECK (stage IN ('understand', 'implement', 'ship', 'done')),
        terminal_state TEXT CHECK (terminal_state IN (NULL, 'failed', 'stalled')),
        reset_count INTEGER NOT NULL DEFAULT 0,
        completed_stages TEXT,
        blocked_reason TEXT,
        pending_approval INTEGER NOT NULL DEFAULT 0,
        session_id TEXT,
        branch TEXT,
        commit_sha TEXT,
        pr_number INTEGER,
        pr_url TEXT,
        worktree_paths TEXT,
        ci_status TEXT CHECK (ci_status IN (NULL, 'pending', 'pass', 'fail')),
        review_status TEXT CHECK (review_status IN (NULL, 'pending', 'pass', 'fail')),
        fail_reason TEXT,
        recoverable INTEGER NOT NULL DEFAULT 1,
        tokens_in INTEGER NOT NULL DEFAULT 0,
        tokens_out INTEGER NOT NULL DEFAULT 0,
        cost_usd REAL NOT NULL DEFAULT 0.0,
        last_heartbeat TEXT,
        heartbeat_timeout_seconds INTEGER NOT NULL DEFAULT 120,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      INSERT INTO runs_new (
        id, task_id, agent_id, parent_run_id, stage, terminal_state,
        reset_count, completed_stages, blocked_reason, pending_approval,
        session_id, branch, commit_sha, pr_number, pr_url, worktree_paths,
        ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, created_at, updated_at
      )
      SELECT
        id, task_id, agent_id, parent_run_id,
        CASE stage
          WHEN 'read-analyze' THEN 'understand'
          WHEN 'create-branch' THEN 'implement'
          WHEN 'baseline-verify' THEN 'implement'
          WHEN 'implement' THEN 'implement'
          WHEN 'local-verify' THEN 'ship'
          WHEN 'external-review' THEN 'ship'
          WHEN 'docs-update' THEN 'ship'
          WHEN 'push-pr' THEN 'ship'
          WHEN 'ci-green' THEN 'ship'
          WHEN 'done' THEN 'done'
          ELSE 'understand'
        END AS stage,
        terminal_state, reset_count, completed_stages, blocked_reason,
        pending_approval, session_id, branch, commit_sha, pr_number, pr_url,
        worktree_paths, ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, created_at, updated_at
      FROM runs;

      DROP TABLE runs;
      ALTER TABLE runs_new RENAME TO runs;

      CREATE INDEX IF NOT EXISTS idx_runs_task_id ON runs(task_id);
      CREATE INDEX IF NOT EXISTS idx_runs_session_id ON runs(session_id) WHERE session_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_runs_stage ON runs(stage) WHERE stage NOT IN ('done');
      CREATE INDEX IF NOT EXISTS idx_runs_terminal ON runs(terminal_state) WHERE terminal_state IS NOT NULL;
    `,
  },
  {
    id: '015_activity_tool_result_kind',
    sql: `
      -- Add tool_result to run_activity kind check constraint.
      -- SQLite can't ALTER CHECK constraints, so rebuild the table.
      CREATE TABLE run_activity_new (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id TEXT NOT NULL REFERENCES runs(id),
        kind TEXT NOT NULL CHECK (kind IN ('tool_call', 'tool_result', 'text', 'summary', 'result')),
        content TEXT NOT NULL DEFAULT '',
        tool_name TEXT,
        created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
      );
      INSERT INTO run_activity_new SELECT * FROM run_activity;
      DROP TABLE run_activity;
      ALTER TABLE run_activity_new RENAME TO run_activity;
      CREATE INDEX IF NOT EXISTS idx_run_activity_run ON run_activity(run_id);
    `,
  },
  {
    id: '016_run_completion_summary',
    sql: 'ALTER TABLE runs ADD COLUMN completion_summary TEXT;',
  },
  {
    id: '017_agent_pricing_override',
    sql: 'ALTER TABLE agents ADD COLUMN pricing TEXT;',
  },
  {
    id: '018_session_run_harness_id',
    // Stores the harness's stable session id (codex Thread.id, claude
    // session uuid). Captured after the first stream event so the cost
    // scanner can look up the matching log file. Distinct from
    // session_id, which is the synthetic ductum-side mapping key.
    sql: 'ALTER TABLE session_run_mapping ADD COLUMN harness_session_id TEXT;',
  },
  {
    id: '019_spec_max_fix_iterations',
    // Per-spec override for the fix-loop iteration cap. NULL → use the
    // factory-wide default from postCompletion.maxFixIterations. Set
    // by the spec import flow when `maxFixIterations` is in the spec
    // YAML/markdown frontmatter.
    sql: 'ALTER TABLE specs ADD COLUMN max_fix_iterations INTEGER;',
  },
  {
    id: '020_gate_evaluations_observed',
    // Observer mode (Priority 3): when factory.workflow.observer=true
    // the enforcement manager still evaluates every tool call against
    // the Edictum workflow runtime and records the would-have-been
    // decision in gate_evaluations, but returns allowed=true to the
    // caller regardless. Operators can query `WHERE observed = 1` to
    // see the "what would have blocked" view without actually blocking
    // real work. 0 = real enforcement decision, 1 = observer-mode
    // dry-run recording.
    sql: 'ALTER TABLE gate_evaluations ADD COLUMN observed INTEGER NOT NULL DEFAULT 0;',
  },
  {
    id: '021_agent_effort',
    sql: 'ALTER TABLE agents ADD COLUMN effort TEXT;',
  },
  {
    id: '022_targets',
    sql: `
      CREATE TABLE IF NOT EXISTS targets (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(project_id, name)
      );

      CREATE INDEX IF NOT EXISTS idx_targets_project ON targets(project_id);
    `,
  },
  {
    id: '023_config_resources',
    sql: `
      CREATE TABLE IF NOT EXISTS config_resources (
        id TEXT PRIMARY KEY,
        kind TEXT NOT NULL CHECK (kind IN ('WorkflowProfile', 'Model', 'Harness', 'SandboxProfile', 'NotificationChannel')),
        project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(kind, project_id, name)
      );

      CREATE UNIQUE INDEX IF NOT EXISTS idx_config_resources_factory_name
        ON config_resources(kind, name)
        WHERE project_id IS NULL;
      CREATE INDEX IF NOT EXISTS idx_config_resources_project ON config_resources(project_id);
    `,
  },
  {
    id: '024_task_targets',
    sql: `
      ALTER TABLE tasks ADD COLUMN target_id TEXT REFERENCES targets(id) ON DELETE SET NULL;
      CREATE INDEX IF NOT EXISTS idx_tasks_target ON tasks(target_id);
    `,
  },
  {
    id: '025_agent_resource_refs',
    sql: "ALTER TABLE agents ADD COLUMN resource_refs TEXT NOT NULL DEFAULT '{}';",
  },
  {
    id: '026_run_runtime_agent_snapshot',
    sql: `
      ALTER TABLE runs ADD COLUMN runtime_model TEXT;
      ALTER TABLE runs ADD COLUMN runtime_harness TEXT;
    `,
  },
  {
    id: '027_harness_string_columns',
    sql: `
      CREATE TABLE agents_new (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        model TEXT NOT NULL,
        harness TEXT NOT NULL,
        resource_refs TEXT NOT NULL DEFAULT '{}',
        capabilities TEXT NOT NULL DEFAULT '[]',
        effort TEXT,
        cost_tier INTEGER NOT NULL DEFAULT 50,
        spawn_config TEXT NOT NULL DEFAULT '{}',
        pricing TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO agents_new (
        id, name, model, harness, resource_refs, capabilities, effort,
        cost_tier, spawn_config, pricing, created_at
      )
      SELECT
        id, name, model, harness, resource_refs, capabilities, effort,
        cost_tier, spawn_config, pricing, created_at
      FROM agents;
      DROP TABLE agents;
      ALTER TABLE agents_new RENAME TO agents;

      CREATE TABLE session_run_mapping_new (
        session_id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        harness TEXT NOT NULL,
        control_token TEXT NOT NULL,
        working_dir TEXT,
        harness_session_id TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO session_run_mapping_new (
        session_id, run_id, harness, control_token, working_dir, harness_session_id, created_at
      )
      SELECT session_id, run_id, harness, control_token, working_dir, harness_session_id, created_at
      FROM session_run_mapping;
      DROP TABLE session_run_mapping;
      ALTER TABLE session_run_mapping_new RENAME TO session_run_mapping;
    `,
  },
  {
    id: '028_run_runtime_sandbox_snapshot',
    sql: 'ALTER TABLE runs ADD COLUMN runtime_sandbox_profile TEXT;',
  },
  {
    id: '029_run_runtime_workflow_profile',
    sql: 'ALTER TABLE runs ADD COLUMN runtime_workflow_profile TEXT;',
  },
  {
    id: '030_spec_status_failed',
    // Widens the specs.status CHECK constraint to allow 'failed' so an
    // operator can mark a spec terminal without forging a 'done'. Pure
    // enum widening — no data migration. SQLite cannot ALTER CHECK in
    // place, so rebuild the table; defer_foreign_keys keeps child rows
    // (tasks, etc.) from raising FK errors mid-rebuild.
    sql: `
      CREATE TABLE specs_new (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft'
          CHECK (status IN ('draft', 'reviewed', 'approved', 'implementing', 'done', 'failed')),
        document TEXT NOT NULL DEFAULT '',
        max_fix_iterations INTEGER,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO specs_new (id, project_id, name, status, document, max_fix_iterations, created_at, updated_at)
      SELECT id, project_id, name, status, document, max_fix_iterations, created_at, updated_at
      FROM specs;
      DROP TABLE specs;
      ALTER TABLE specs_new RENAME TO specs;
    `,
  },
  {
    id: '031_task_budget_extra_usd',
    // Operator-granted extra cap (USD) added to perRunHardUsd for runs of
    // this task. Decision 114 (budget cap as gate). Persists across
    // retries so an extension survives the implicit re-dispatch path.
    sql: 'ALTER TABLE tasks ADD COLUMN budget_extra_usd REAL NOT NULL DEFAULT 0;',
  },
  {
    id: '032_task_turn_extra_count',
    // Operator-granted extra Claude Agent SDK turn budget added to the
    // global default (claude.ts maxTurns) for runs of this task.
    // Decision 118 (max-turns cap as gate). Same shape as 031 but for a
    // distinct runtime resource. Persists across retries.
    sql: 'ALTER TABLE tasks ADD COLUMN turn_extra_count INTEGER NOT NULL DEFAULT 0;',
  },
  {
    id: '033_run_verify_retries',
    // Factory-owned verification retry count. Used for the D138 last
    // fix-iteration retry so duplicate routing cannot silently retry
    // verification more than once for the same run.
    sql: 'ALTER TABLE runs ADD COLUMN verify_retries INTEGER NOT NULL DEFAULT 0;',
  },
  {
    id: '034_run_terminal_cancelled',
    // Widen terminal_state for D145 operator cancel. SQLite cannot
    // ALTER a CHECK constraint in place, so rebuild runs with the
    // same columns and indexes plus 'cancelled'.
    sql: `
      CREATE TABLE runs_new (
        id TEXT PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        agent_id TEXT NOT NULL REFERENCES agents(id),
        parent_run_id TEXT REFERENCES runs_new(id),
        stage TEXT NOT NULL DEFAULT 'understand'
          CHECK (stage IN ('understand', 'implement', 'ship', 'done')),
        terminal_state TEXT CHECK (terminal_state IN (NULL, 'failed', 'stalled', 'cancelled')),
        reset_count INTEGER NOT NULL DEFAULT 0,
        completed_stages TEXT,
        blocked_reason TEXT,
        pending_approval INTEGER NOT NULL DEFAULT 0,
        session_id TEXT,
        branch TEXT,
        commit_sha TEXT,
        pr_number INTEGER,
        pr_url TEXT,
        worktree_paths TEXT,
        runtime_model TEXT,
        runtime_harness TEXT,
        runtime_sandbox_profile TEXT,
        runtime_workflow_profile TEXT,
        ci_status TEXT CHECK (ci_status IN (NULL, 'pending', 'pass', 'fail')),
        review_status TEXT CHECK (review_status IN (NULL, 'pending', 'pass', 'fail')),
        fail_reason TEXT,
        recoverable INTEGER NOT NULL DEFAULT 1,
        tokens_in INTEGER NOT NULL DEFAULT 0,
        tokens_out INTEGER NOT NULL DEFAULT 0,
        cost_usd REAL NOT NULL DEFAULT 0.0,
        last_heartbeat TEXT,
        heartbeat_timeout_seconds INTEGER NOT NULL DEFAULT 120,
        verify_retries INTEGER NOT NULL DEFAULT 0,
        completion_summary TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO runs_new (
        id, task_id, agent_id, parent_run_id, stage, terminal_state,
        reset_count, completed_stages, blocked_reason, pending_approval,
        session_id, branch, commit_sha, pr_number, pr_url, worktree_paths,
        runtime_model, runtime_harness, runtime_sandbox_profile, runtime_workflow_profile,
        ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, verify_retries, completion_summary,
        created_at, updated_at
      )
      SELECT
        id, task_id, agent_id, parent_run_id, stage, terminal_state,
        reset_count, completed_stages, blocked_reason, pending_approval,
        session_id, branch, commit_sha, pr_number, pr_url, worktree_paths,
        runtime_model, runtime_harness, runtime_sandbox_profile, runtime_workflow_profile,
        ci_status, review_status, fail_reason, recoverable,
        tokens_in, tokens_out, cost_usd, last_heartbeat,
        heartbeat_timeout_seconds, verify_retries, completion_summary,
        created_at, updated_at
      FROM runs;
      DROP TABLE runs;
      ALTER TABLE runs_new RENAME TO runs;
      CREATE INDEX IF NOT EXISTS idx_runs_task_id ON runs(task_id);
      CREATE INDEX IF NOT EXISTS idx_runs_session_id ON runs(session_id) WHERE session_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_runs_stage ON runs(stage) WHERE stage NOT IN ('done');
      CREATE INDEX IF NOT EXISTS idx_runs_terminal ON runs(terminal_state) WHERE terminal_state IS NOT NULL;
    `,
  },
  {
    id: '035_exit_demo_evidence_type',
    // Widen evidence.type for P5's typed exit demo ledger row. SQLite
    // cannot ALTER a CHECK constraint in place, so rebuild the table.
    sql: `
      CREATE TABLE evidence_new (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL REFERENCES runs(id),
        type TEXT NOT NULL CHECK (type IN ('ci', 'review', 'test', 'lint', 'custom', 'exit_demo.run')),
        payload TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      INSERT INTO evidence_new (id, run_id, type, payload, created_at)
      SELECT id, run_id, type, payload, created_at
      FROM evidence;
      DROP TABLE evidence;
      ALTER TABLE evidence_new RENAME TO evidence;
      CREATE INDEX IF NOT EXISTS idx_evidence_run ON evidence(run_id);
    `,
  },
  {
    id: '036_repositories_components',
    sql: `
      CREATE TABLE IF NOT EXISTS repositories (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(project_id, name)
      );

      CREATE TABLE IF NOT EXISTS components (
        id TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(repository_id, name)
      );

      CREATE INDEX IF NOT EXISTS idx_repositories_project ON repositories(project_id);
      CREATE INDEX IF NOT EXISTS idx_components_repository ON components(repository_id);
      ALTER TABLE tasks ADD COLUMN repository_id TEXT REFERENCES repositories(id) ON DELETE SET NULL;
      ALTER TABLE tasks ADD COLUMN component_id TEXT REFERENCES components(id) ON DELETE SET NULL;
      CREATE INDEX IF NOT EXISTS idx_tasks_repository ON tasks(repository_id);
      CREATE INDEX IF NOT EXISTS idx_tasks_component ON tasks(component_id);
    `,
  },
  {
    id: '037_run_attempt_snapshot',
    sql: 'ALTER TABLE runs ADD COLUMN attempt_snapshot TEXT;',
  },
  {
    id: '038_factory_settings_foundation',
    sql: `
      CREATE TABLE IF NOT EXISTS factory_runtime_settings (
        factory_id TEXT PRIMARY KEY REFERENCES factories(id) ON DELETE CASCADE,
        api_bind_host TEXT,
        api_port INTEGER CHECK (api_port IS NULL OR (api_port >= 1 AND api_port <= 65535)),
        public_api_url TEXT,
        dashboard_url TEXT,
        dispatcher_enabled INTEGER CHECK (dispatcher_enabled IS NULL OR dispatcher_enabled IN (0, 1)),
        dispatcher_heartbeat_interval_seconds INTEGER
          CHECK (
            dispatcher_heartbeat_interval_seconds IS NULL
            OR dispatcher_heartbeat_interval_seconds > 0
          ),
        worktree_enabled INTEGER CHECK (worktree_enabled IS NULL OR worktree_enabled IN (0, 1)),
        worktree_base_path TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE TABLE IF NOT EXISTS factory_secret_metadata (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        scope TEXT NOT NULL CHECK (scope IN ('factory', 'project')),
        project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
        description TEXT,
        status TEXT NOT NULL CHECK (status IN ('configured', 'missing', 'test_failed', 'unknown')),
        key_source_type TEXT NOT NULL CHECK (key_source_type IN ('local-file')),
        key_source_id TEXT NOT NULL,
        last_rotated_at TEXT,
        last_tested_at TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        CHECK (
          (scope = 'factory' AND project_id IS NULL)
          OR (scope = 'project' AND project_id IS NOT NULL)
        )
      );

      CREATE TABLE IF NOT EXISTS factory_secret_payloads (
        secret_id TEXT PRIMARY KEY REFERENCES factory_secret_metadata(id) ON DELETE CASCADE,
        algorithm TEXT NOT NULL,
        ciphertext TEXT NOT NULL,
        nonce TEXT NOT NULL,
        auth_tag TEXT,
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

      CREATE UNIQUE INDEX IF NOT EXISTS idx_factory_secret_factory_name
        ON factory_secret_metadata(name)
        WHERE project_id IS NULL;
      CREATE UNIQUE INDEX IF NOT EXISTS idx_factory_secret_project_name
        ON factory_secret_metadata(project_id, name)
        WHERE project_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_factory_secret_project
        ON factory_secret_metadata(project_id);
    `,
  },
  {
    id: '039_best_of_n_strategy_metadata',
    sql: '-- applied by applyMigration for guarded ALTER TABLEs and legacy backfill',
  },
  {
    id: '040_factory_view_state',
    sql: `
      CREATE TABLE IF NOT EXISTS factory_view_state (
        factory_id TEXT PRIMARY KEY REFERENCES factories(id) ON DELETE CASCADE,
        home_last_seen_at TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
    `,
  },
  {
    id: '041_evidence_content_addressing',
    sql: `
      ALTER TABLE evidence ADD COLUMN content_sha TEXT;
      CREATE UNIQUE INDEX IF NOT EXISTS idx_evidence_run_content
        ON evidence(run_id, content_sha);
    `,
  },
] as const

export type SqliteDatabase = Database.Database

export function applyMigration(
  db: SqliteDatabase,
  migration: (typeof MIGRATIONS)[number],
): void {
  if (migration.id === '003_tasks_required_role') {
    if (!hasColumn(db, 'tasks', 'required_role')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '005_task_retry') {
    if (!hasColumn(db, 'tasks', 'retry_count')) {
      db.exec("ALTER TABLE tasks ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;")
    }
    if (!hasColumn(db, 'tasks', 'retry_after')) {
      db.exec('ALTER TABLE tasks ADD COLUMN retry_after TEXT;')
    }
    return
  }

  if (migration.id === '006_session_run_working_dir') {
    if (!hasColumn(db, 'session_run_mapping', 'working_dir')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '007_session_run_control_token') {
    if (!hasColumn(db, 'session_run_mapping', 'control_token')) {
      db.exec('ALTER TABLE session_run_mapping ADD COLUMN control_token TEXT;')
    }
    db.exec(`
      UPDATE session_run_mapping
        SET control_token = lower(hex(randomblob(32)))
        WHERE control_token IS NULL OR control_token = '';
    `)
    return
  }

  if (migration.id === '009_task_complexity') {
    if (!hasColumn(db, 'tasks', 'complexity')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '010_agent_cost_tier') {
    if (!hasColumn(db, 'agents', 'cost_tier')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '013_worktree_paths') {
    if (!hasColumn(db, 'runs', 'worktree_paths')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '016_run_completion_summary') {
    if (!hasColumn(db, 'runs', 'completion_summary')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '017_agent_pricing_override') {
    if (!hasColumn(db, 'agents', 'pricing')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '018_session_run_harness_id') {
    if (!hasColumn(db, 'session_run_mapping', 'harness_session_id')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '019_spec_max_fix_iterations') {
    if (!hasColumn(db, 'specs', 'max_fix_iterations')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '020_gate_evaluations_observed') {
    if (!hasColumn(db, 'gate_evaluations', 'observed')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '021_agent_effort') {
    if (!hasColumn(db, 'agents', 'effort')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '024_task_targets') {
    if (!hasColumn(db, 'tasks', 'target_id')) {
      db.exec('ALTER TABLE tasks ADD COLUMN target_id TEXT REFERENCES targets(id) ON DELETE SET NULL;')
    }
    db.exec('CREATE INDEX IF NOT EXISTS idx_tasks_target ON tasks(target_id);')
    return
  }

  if (migration.id === '025_agent_resource_refs') {
    if (!hasColumn(db, 'agents', 'resource_refs')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '026_run_runtime_agent_snapshot') {
    if (!hasColumn(db, 'runs', 'runtime_model')) {
      db.exec('ALTER TABLE runs ADD COLUMN runtime_model TEXT;')
    }
    if (!hasColumn(db, 'runs', 'runtime_harness')) {
      db.exec('ALTER TABLE runs ADD COLUMN runtime_harness TEXT;')
    }
    return
  }

  if (migration.id === '028_run_runtime_sandbox_snapshot') {
    if (!hasColumn(db, 'runs', 'runtime_sandbox_profile')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '029_run_runtime_workflow_profile') {
    if (!hasColumn(db, 'runs', 'runtime_workflow_profile')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '031_task_budget_extra_usd') {
    if (!hasColumn(db, 'tasks', 'budget_extra_usd')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '032_task_turn_extra_count') {
    if (!hasColumn(db, 'tasks', 'turn_extra_count')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '033_run_verify_retries') {
    if (!hasColumn(db, 'runs', 'verify_retries')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '036_repositories_components') {
    db.exec(`
      CREATE TABLE IF NOT EXISTS repositories (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(project_id, name)
      );
      CREATE TABLE IF NOT EXISTS components (
        id TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        spec TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE(repository_id, name)
      );
      CREATE INDEX IF NOT EXISTS idx_repositories_project ON repositories(project_id);
      CREATE INDEX IF NOT EXISTS idx_components_repository ON components(repository_id);
    `)
    if (!hasColumn(db, 'tasks', 'repository_id')) {
      db.exec('ALTER TABLE tasks ADD COLUMN repository_id TEXT REFERENCES repositories(id) ON DELETE SET NULL;')
    }
    if (!hasColumn(db, 'tasks', 'component_id')) {
      db.exec('ALTER TABLE tasks ADD COLUMN component_id TEXT REFERENCES components(id) ON DELETE SET NULL;')
    }
    db.exec(`
      CREATE INDEX IF NOT EXISTS idx_tasks_repository ON tasks(repository_id);
      CREATE INDEX IF NOT EXISTS idx_tasks_component ON tasks(component_id);
    `)
    return
  }

  if (migration.id === '037_run_attempt_snapshot') {
    if (!hasColumn(db, 'runs', 'attempt_snapshot')) {
      db.exec(migration.sql)
    }
    return
  }

  if (migration.id === '039_best_of_n_strategy_metadata') {
    if (!hasColumn(db, 'specs', 'strategy')) {
      db.exec(`
        ALTER TABLE specs ADD COLUMN strategy TEXT NOT NULL DEFAULT 'normal'
          CHECK (strategy IN ('normal', 'best_of_n'));
      `)
    }
    if (!hasColumn(db, 'specs', 'strategy_config')) {
      db.exec('ALTER TABLE specs ADD COLUMN strategy_config TEXT;')
    }
    if (!hasColumn(db, 'tasks', 'strategy_role')) {
      db.exec(`
        ALTER TABLE tasks ADD COLUMN strategy_role TEXT NOT NULL DEFAULT 'normal'
          CHECK (strategy_role IN ('normal', 'candidate', 'blind_review'));
      `)
    }
    if (!hasColumn(db, 'tasks', 'strategy_group')) {
      db.exec('ALTER TABLE tasks ADD COLUMN strategy_group TEXT;')
    }
    backfillLegacyBakeoffStrategyMetadata(db)
    db.exec(`
      CREATE INDEX IF NOT EXISTS idx_specs_strategy ON specs(strategy);
      CREATE INDEX IF NOT EXISTS idx_tasks_strategy_group ON tasks(strategy_group)
        WHERE strategy_group IS NOT NULL;
    `)
    return
  }

  db.exec(migration.sql)
}

function hasColumn(db: SqliteDatabase, table: string, column: string): boolean {
  return db.prepare(`SELECT 1 FROM pragma_table_info('${table}') WHERE name = ?`).get(column) != null
}

function backfillLegacyBakeoffStrategyMetadata(db: SqliteDatabase): void {
  db.prepare(`
    UPDATE specs
      SET strategy = 'best_of_n'
      WHERE strategy = 'normal'
        AND instr(document, ?) > 0
  `).run(LEGACY_BAKEOFF_SPEC_MARKER)
  db.prepare(`
    UPDATE tasks
      SET strategy_role = 'candidate',
          strategy_group = 'legacy-' || spec_id
      WHERE strategy_role = 'normal'
        AND (strategy_group IS NULL OR strategy_group = '')
        AND name LIKE 'candidate-%'
        AND spec_id IN (
          SELECT id FROM specs
          WHERE strategy = 'best_of_n'
            AND instr(document, ?) > 0
        )
  `).run(LEGACY_BAKEOFF_SPEC_MARKER)
  db.prepare(`
    UPDATE tasks
      SET strategy_role = 'blind_review',
          strategy_group = 'legacy-' || spec_id
      WHERE strategy_role = 'normal'
        AND (strategy_group IS NULL OR strategy_group = '')
        AND name = 'blind-review'
        AND spec_id IN (
          SELECT id FROM specs
          WHERE strategy = 'best_of_n'
            AND instr(document, ?) > 0
        )
  `).run(LEGACY_BAKEOFF_SPEC_MARKER)
}
